In [1]:
import numpy as np

# Stock A price matrix (Open, High, Low for 5 days)
stock_A = np.array([
    [100, 105, 98],
    [102, 108, 101],
    [104, 110, 103],
    [103, 109, 100],
    [105, 111, 104]
])

# Stock B price matrix (Open, High, Low for 5 days)
stock_B = np.array([
    [98, 103, 95],
    [100, 106, 99],
    [102, 108, 101],
    [101, 107, 97],
    [103, 109, 100]
])

# Element-wise sum
sum_matrix = stock_A + stock_B

# Element-wise difference
diff_matrix = stock_A - stock_B

# Display results
print("Stock A Data:\n", stock_A)
print("\nStock B Data:\n", stock_B)

print("\nElement-wise Sum of Matrices:\n", sum_matrix)

print("\nElement-wise Difference of Matrices:\n", diff_matrix)

Stock A Data:
 [[100 105  98]
 [102 108 101]
 [104 110 103]
 [103 109 100]
 [105 111 104]]

Stock B Data:
 [[ 98 103  95]
 [100 106  99]
 [102 108 101]
 [101 107  97]
 [103 109 100]]

Element-wise Sum of Matrices:
 [[198 208 193]
 [202 214 200]
 [206 218 204]
 [204 216 197]
 [208 220 204]]

Element-wise Difference of Matrices:
 [[2 2 3]
 [2 2 2]
 [2 2 2]
 [2 2 3]
 [2 2 4]]
